"""add_marks_index_for_ranking

Revision ID: bbf14bf30e63
Revises: 9aa88ff91a82
Create Date: 2026-08-13 06:50:35.678517+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbf14bf30e63'
down_revision = '9aa88ff91a82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_exam_score_marks_desc', 'exam_score_submissions', ['exam_id', 'marks_obtained'], unique=False, postgresql_using='btree')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_exam_score_marks_desc', table_name='exam_score_submissions', postgresql_using='btree')
    # ### end Alembic commands ###
